### PR TITLE
Edit README

### PR DESCRIPTION
**Pull request by daniele-proverbio**
Small editings, added troubleshooting section

### CODE REVIEW

**Comment by laurentheirendt** [comment]
I think @exaexa already made some changes, but on the `develop` branch. I changed the base of this MR. Can you check?

**Review by laurentheirendt — CHANGES_REQUESTED** [review]
this needs to be merged with the current version on `develop`

**Comment by daniele-proverbio** [comment]
Conflicts resolved, can be merged

**Review by exaexa — APPROVED** [review]
Perfect, thanks a lot!

**Review by laurentheirendt — APPROVED** [review]

**Pull request merged**
