### PR TITLE
Changes to check

### PR DESCRIPTION
**Pull request by laurentheirendt**
- simplification
- remove check on file name

@daniele-proverbio, can you check so that we can make #24 work?

### CODE REVIEW

**Review by daniele-proverbio — COMMENTED** [review]
Why did you remove the check on file name? Is it for out testing, or for good? I think it could be a first buffer to avoid them uploading random stuff

**Comment by laurentheirendt** [comment]
I removed the check as I don't see the value in it. Basically, any file can be uploaded with any name. The web interface will rename the file to `input-data.xlsx` and store it in the `input` directory. So the name of the input file itself does not matter.

**Comment by daniele-proverbio** [comment]
I agree than any wrong file will not pass the subsequent checks, but I would nonetheless alert a ministry employee that he\she's using a wrong file. Their pipeline is to always update this specific file with this specific name (which was agreed upon with the Taskforce); if they change it by accident, I believe they should be notified

**Comment by laurentheirendt** [comment]
Okay fair point - I will put it back then

**Comment by daniele-proverbio** [comment]
Ok, let me know when to pull :)

**Comment by laurentheirendt** [comment]
I added it now as a first check and then a warning before moving the file. That way, the file handling/moving/renaming is done as part of the pipeline itself.

**Review by daniele-proverbio — APPROVED** [review]

**Pull request merged**
